version: "3"
services:
  encryptzia:
    image: registry.jonas.domains/timesz/encryptzia:stable
    user: root
    volumes:
      - ./app:/var/lib/encryptzia:rw
      - ./app/app.log:/var/log/encryptzia.log:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - 5678:5678
    environment:
      - DISPLAY=$DISPLAY
      - XDG_RUNTIME_DIR=/run/user/0
    devices:
      - "/dev/dri:/dev/dri"
    container_name: encryptzia
    entrypoint: "sleep infinity"
